# Generated by Django 4.2.7 on 2023-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_alter_team_team_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_lead_id',
            field=models.IntegerField(null=True),
        ),
    ]
