# Generated by Django 4.2.7 on 2023-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
